Ispiti/NPP - 2014×2015/2019-11-04/Rjesenje/RS1_2019_11_04/ViewModels/AjaxStavkeRezultatiVM.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RS1_2019_11_04.ViewModels
{
    public class AjaxStavkeRezultatiVM
    {
        public int PopravniIspitId { get; set; }
        public List<Row> Rows { get; set; }
        public class Row
        {
            public int StavkaPopravniIspitId { get; set; }
            public string UcenikImePrezime { get; set; }
            public string Odjeljenje { get; set; }
            public int BrojUDnevniku { get; set; }
            public bool? IsPristupio { get; set; }
            public int Bodovi { get; set; }
        }
    }
}

Ispiti/NPP - 2014×2015/2019-11-04/Rjesenje/RS1_2019_11_04/ViewModels/AjaxStavkeUrediVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RS1_2019_11_04.ViewModels
{
    public class AjaxStavkeUrediVM
    {
        public int PopravniIspitStavkaId { get; set; }
        public string ImePrezime { get; set; }
        public int Bodovi { get; set; }
    }
}

Ispiti/NPP - 2014×2015/2019-11-04/Rjesenje/RS1_2019_11_04/ViewModels/PopravniIspitDodajVM.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RS1_2019_11_04.ViewModels
{
    public class PopravniIspitDodajVM
    {
        public int PredmetId { get; set; }
        public string Predmet { get; set; }
        public string Razred { get; set; }
        public string DatumIspita { get; set; }
        public int SkolaId { get; set; }
        public List<SelectListItem> Skole { get; set; }
        public int SkolskaGodinaId { get; set; }
        public List<SelectListItem> SkolskeGodine { get; set; }
    }
}

Ispiti/NPP - 2014×2015/2019-11-04/Rjesenje/RS1_2019_11_04/ViewModels/PopravniIspitIndexVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RS1_2019_11_04.ViewModels
{
    public class PopravniIspitIndexVM
    {
        public List<Row> Rows { get; set; }
        public class Row
        {
            public int PredmetId { get; set; }
            public string Razred { get; set; }
            public string Predmet { get; set; }
        }
    }
}

Ispiti/NPP - 2014×2015/2019-11-04/Rjesenje/RS1_2019_11_04/ViewModels/PopravniIspitOdaberiVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RS1_2019_11_04.ViewModels
{
    public class PopravniIspitOdaberiVM
    {
        public int PredmetId { get; set; }
        public string Predmet { get; set; }
        public string Razred { get; set; }
        public List<Row> Rows { get; set; }
        public class Row
        {
            public int PopravniIspitId { get; set; }
            public string Skola { get; set; }
            public string SkolskaGodina { get; set; }
            public string DatumIspita { get; set; }
            public int BrojUcenikaNaIspitu { get; set; }
            public int BrojUcenikaKojiSuPolozili { get; set; }
        }
    }
}

Ispiti/NPP - 2014×2015/2019-11-04/Rjesenje/RS1_2019_11_04/ViewModels/PopravniIspitUrediVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RS1_2019_11_04.ViewModels
{
    public class PopravniIspitUrediVM
    {
        public int PopravniIspitId { get; set; }
        public int PredmetId { get; set; }
        public string Predmet { get; set; }
        public string Razred { get; set; }
        public DateTime DatumIspita { get; set; }
        public int SkolaId { get; set; }
        public string Skola { get; set; }
        public int SkolskaGodinaId { get; set; }
        public string SkolskaGodina { get; set; }
    }
}

Ispiti/NPP - 2014×2015/2019-11-04/Rjesenje/RS1_2019_11_04/Controllers/AjaxStavkeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RS1_2019_11_04.EF;
using RS1_2019_11_04.ViewModels;

namespace RS1_2019_11_04.Controllers
{
    public class AjaxStavkeController : Controller
    {
        private readonly MojContext ctx;

        public AjaxStavkeController(MojContext context)
        {
            ctx = context;
        }

        public IActionResult Index(int id)
        {
            var Ispit = ctx.PopravniIspit.Find(id);
            var model = new AjaxStavkeRezultatiVM
            {
                PopravniIspitId = id,
                Rows = ctx.PopravniIspitStavka
                    .Where
                    (
                        i => i.PopravniIspitId == id
                    )
                    .Select
                    (
                        i => new AjaxStavkeRezultatiVM.Row
                        {
                            StavkaPopravniIspitId = i.Id,
                            UcenikImePrezime = i.OdjeljenjeStavka.Ucenik.ImePrezime,
                            BrojUDnevniku = i.OdjeljenjeStavka.BrojUDnevniku,
                            Odjeljenje = i.OdjeljenjeStavka.Odjeljenje.Oznaka,
                            IsPristupio = i.IsPristupio,
                            Bodovi = i.Bodovi
                        }
                    )
                    .ToList()
            };
            return PartialView(model);
        }

        public IActionResult UpdateBodovi(int id, int bodovi)
        {
            var Stavka = ctx.PopravniIspitStavka.Find(id);
            Stavka.Bodovi = bodovi;
            ctx.SaveChanges();
            return Redirect("/PopravniIspit/Uredi/" + Stavka.PopravniIspitId);
        }

        public IActionResult Uredi(int id)
        {
            var Stavka = ctx.PopravniIspitStavka
                .Include(i => i.OdjeljenjeStavka)
                .Include(i => i.OdjeljenjeStavka.Ucenik)
                .Where(i => i.Id == id)
                .SingleOrDefault();

            var model = new AjaxStavkeUrediVM
            {
                PopravniIspitStavkaId = id,
                ImePrezime = Stavka.OdjeljenjeStavka.Ucenik.ImePrezime,
                Bodovi = Stavka.Bodovi
            };
            return PartialView(model);
        }

        public IActionResult Snimi(AjaxStavkeUrediVM model)
        {
            var Stavka = ctx.PopravniIspitStavka.Find(model.PopravniIspitStavkaId);
            Stavka.Bodovi = model.Bodovi;
            ctx.SaveChanges();
            return Redirect("/AjaxStavke/Index/" + Stavka.PopravniIspitId);
        }
        
    }
}

Ispiti/NPP - 2014×2015/2019-11-04/Rjesenje/RS1_2019_11_04/Controllers/AjaxTestController.cs
using Microsoft.AspNetCore.Mvc;

namespace RS1_2019_11_04.Controllers
{
    public class AjaxTestController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AjaxTestAction()
        {
            return PartialView("_AjaxTestView");
        }
    }
}

Ispiti/NPP - 2014×2015/2019-11-04/Rjesenje/RS1_2019_11_04/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RS1_2019_11_04.EF;

namespace RS1_2019_11_04.Controllers
{
    public class HomeController : Controller
    {
        private MojContext _context;

        public HomeController(MojContext context)
        {
            _context = context;
        }


        public IActionResult Index()
        {
            return View();
        }

        public IActionResult TestDB()
        {
            MojDBInitializer.Izvrsi(_context);
            return View(_context); 
        }

     
    }
}

Ispiti/NPP - 2014×2015/2019-11-04/Rjesenje/RS1_2019_11_04/Controllers/LoginController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using RS1_2019_11_04.EF;


namespace RS1_2019_11_04.Controllers
{
    public class LoginController : Controller
    {
        private MojContext _db;

        public LoginController(MojContext db)
        {
            _db = db;
        }

        public ActionResult Index()
        {
            return View();
        }

      
    }
}

Ispiti/NPP - 2014×2015/2019-11-04/Rjesenje/RS1_2019_11_04/Views/AjaxStavke/Index.cshtml
@model RS1_2019_11_04.ViewModels.AjaxStavkeRezultatiVM
@{
    ViewData["Title"] = "Index";
}

<table class="table table-bordered">
    <thead>
        <tr>
            <td>Učenik</td>
            <td>Odjeljenje</td>
            <td>Broj u dnevniku</td>
            <td>Pristupio ispitu</td>
            <td>Bodovi</td>
            <td>Akcija</td>
        </tr>
    </thead>
    <tbody>
        @for(int i = 1; i <= Model.Rows.Count(); i++)
        {
            <tr>
                <td>@i. @Model.Rows[i - 1].UcenikImePrezime</td>
                <td>@Model.Rows[i - 1].Odjeljenje</td>
                <td>@Model.Rows[i - 1].BrojUDnevniku</td>
                @if (Model.Rows[i - 1].IsPristupio == true)
                {
                    <td><a class="btn btn-success" 
                           asp-controller="PopravniIspit" 
                           asp-action="UcenikJeOdsutan" 
                           asp-route-id="@Model.Rows[i - 1].StavkaPopravniIspitId">DA</a>
                    </td>
                    <td><input class="Bodovi" type="number" value="@Model.Rows[i - 1].Bodovi" id="@Model.Rows[i - 1].StavkaPopravniIspitId" /></td>
                    <td>
                        <a asp-route-id="@Model.Rows[i - 1].StavkaPopravniIspitId"
                           asp-controller="AjaxStavke"
                           asp-action="Uredi"
                           ajax-poziv="da"
                           ajax-rezultat="AjaxDiv"
                           ajax-url="/AjaxStavke/Uredi?id=@Model.Rows[i - 1].StavkaPopravniIspitId">Uredi</a>
                    </td>
                }
                else if (Model.Rows[i - 1].IsPristupio == false)
                {
                    <td><a class="btn btn-danger"
                           asp-controller="PopravniIspit" 
                           asp-action="UcenikJePrisutan" 
                           asp-route-id="@Model.Rows[i - 1].StavkaPopravniIspitId">NE</a>
                    </td>
                    <td>X</td>
                    <td></td>
                }
                else
                {
                    <td><p style="color: red">Nema pravno pristupa</p></td>
                    <td>@Model.Rows[i - 1].Bodovi</td>
                    <td></td>
                }
            </tr>
        }
    </tbody>
</table>
<script>
    function UpdateBodovi() {
        $("input.Bodovi").focusout(function (e, response) {
            var id = $(this).attr("id");
            var bodovi = $(this).val();

            if (bodovi >= 0 && bodovi <= 100) {
                $.post("/AjaxStavke/UpdateBodovi?id=" + id + "&bodovi=" + bodovi);
            }
        });
    }

    $(document).ready(function () {
        UpdateBodovi();
    });
    $(document).ajaxComplete(function () {
        UpdateBodovi();
    });
</script>

Ispiti/NPP - 2014×2015/2019-11-04/Rjesenje/RS1_2019_11_04/Views/AjaxStavke/Uredi.cshtml
@model RS1_2019_11_04.ViewModels.AjaxStavkeUrediVM
@{
    ViewData["Title"] = "Uredi";
}

    <form ajax-poziv="da" ajax-rezultat="AjaxDiv" asp-controller="AjaxStavke" asp-action="Snimi">
        <input asp-for="PopravniIspitStavkaId" value="@Model.PopravniIspitStavkaId" hidden />
        <div class="form-group">
            <label asp-for="ImePrezime" class="control-label">Učenik: </label>
            <input asp-for="ImePrezime" value="@Model.ImePrezime" class="form-control" readonly />
        </div>
        <div class="form-group">
            <label asp-for="Bodovi" class="control-label">Bodovi: </label>
            <input asp-for="Bodovi" value="@Model.Bodovi" class="form-control" />
        </div>
        <div class="form-group">
            <input type="submit" value="Snimi"/>
        </div>
    </form>