Ispiti/NPP - 2014×2015/2020-09-18/Postavka/RS1_Ispit/Controllers/AjaxTestController.cs
using Microsoft.AspNetCore.Mvc;

namespace RS1_Ispit_asp.net_core.Controllers
{
    public class AjaxTestController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AjaxTestAction()
        {
            return PartialView("_AjaxTestView");
        }
    }
}

Ispiti/NPP - 2014×2015/2020-09-18/Postavka/RS1_Ispit/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RS1_Ispit_asp.net_core.EF;

namespace RS1_Ispit_asp.net_core.Controllers
{
    public class HomeController : Controller
    {
        private MojContext _context;

        public HomeController(MojContext context)
        {
            _context = context;
        }


        public IActionResult Index()
        {
            return View();
        }

        public IActionResult TestDB()
        {
            MojDBInitializer.Izvrsi(_context);
            return View(_context); 
        }

     
    }
}

Ispiti/NPP - 2014×2015/2020-09-18/Postavka/RS1_Ispit/Views/AjaxTest/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Ovo je index.cshtml</h2>

<label>Pozovi AjaxTestAction i rezultat smjesti u testAjaxDiv</label>

<a asp-action="AjaxTestAction" ajax-poziv="da" ajax-rezultat="testAjaxDiv" class="btn btn-primary">Pokreni</a>

<div style="border: solid; border-color:black">
    <div id="testAjaxDiv">
        Ovo je testAjaxDiv
    </div>

</div>
@Html.ActionLink("Back", "Index", "Home")

Ispiti/NPP - 2014×2015/2020-09-18/Postavka/RS1_Ispit/Views/AjaxTest/_AjaxTestView.cshtml
<h3>Ovo je _AjaxTestView.cshtml čiji layout je null</h3>

Ispiti/NPP - 2014×2015/2020-09-18/Postavka/RS1_Ispit/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";


}

<h2>
    Ovdje upisati broj indeksa!!
</h2>



<br />
@Html.ActionLink("Ajax text", "Index", "AjaxTest")
<br />
@Html.ActionLink("DB text", "TestDB", "Home")   << -- Prije nego što kliknete prepravite Connection string. Upišite vaš broj indeksa u naziv DB-a.
<br />
@Html.ActionLink("Takmicenje/Index", "Index", "Takmicenje") << -- Potrebno implementirati!

Ispiti/NPP - 2014×2015/2020-09-18/Postavka/RS1_Ispit/Views/Home/Proba.cshtml
@{
    ViewData["Title"] = "Proba";
}

<h2>Proba</h2>

Ispiti/NPP - 2014×2015/2020-09-18/Postavka/RS1_Ispit/Views/Home/TestDB.cshtml
@using RS1_Ispit_asp.net_core.EF
@model RS1_Ispit_asp.net_core.EF.MojContext

@{
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Test DB - row count</h2>

DodjeljenPredmet: @Model.DodjeljenPredmet.Count() <br />
Nastavnik: @Model.Nastavnik.Count() <br />
Odjeljenje: @Model.Odjeljenje.Count() <br />
OdjeljenjeStavka: @Model.OdjeljenjeStavka.Count() <br />
PredajePredmet: @Model.PredajePredmet.Count() <br />
Predmet: @Model.Predmet.Count() <br />
Skola: @Model.Skola.Count() <br />
SkolskaGodina: @Model.SkolskaGodina.Count() <br />
Ucenik: @Model.Ucenik.Count() <br />


@Html.ActionLink("Back", "Index")